### PR TITLE
New APIbacklog.md

### LINKED ISSUE #4: Adapt ProjectStructuresAndRoles.MD to changes in API backlog table (reduction of columns)
Before we change our operational processes we should adapt our process descriptions and bring that to a decision (in case of large changes in TSC). 

For the last change in the API backlog table that step is missing.

### PR DESCRIPTION
**Pull request by TEF-RicardoSerr**
#### What type of PR is this?

Add one of the following kinds:
* enhancement/feature

#### What this PR does / why we need it:
This is an enhanced table for the APIBacklog

#### Which issue(s) this PR fixes:

Fixes #4

#### Special notes for reviewers:

To make it colaborative please contribute over my personal root repo ([TEF-RicardoSerr/APIBacklog](https://github.com/TEF-RicardoSerr/APIBacklog/tree/Table)) to make any commit

### CODE REVIEW

**Comment by hdamker** [comment]
@TEF-RicardoSerr thanks - that is indeed a good enhancement. What about to get rid of this super long lines and define the complete table within HTML? That would have the advantage that each table line is a block of HTML code and can be maintained independent. 

See here for an example was is possible with HTML, from the times we had not yet the inline documentation of the APIs: https://github.com/camaraproject/QualityOnDemand/blob/90e15efbe7da77f6739c8efb87091930c0ad4139/documentation/API_documentation/QoD_API.md?plain=1#L91

**Review by caubut-charter — APPROVED** [review]
LGTM as an enhancement!

Seconding @hdamker that markdown tables can be difficult.

HTML, or one of the other formats [GitHub renders](https://docs.github.com/en/repositories/working-with-files/using-files/working-with-non-code-files) may offer some improvements in regards to editing and diffs.

Not a blocker though, so approving.

**Comment by hdamker** [comment]
@jgarciahospital @caubut-charter looking on https://github.com/camaraproject/APIBacklog/pull/80/conflicts I would propose to restart the restructuring with the current content of the table in main (and pause other updates for a few days for this purpose), maybe then directly in HTML.

**Comment by jgarciahospital** [comment]
PR closed as solved in #101

**Pull request closed without merging**
