### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by TEF-RicardoSerr**
**What type of PR is this?**
Add one of the following kinds:
* subproject management

**What this PR does / why we need it:**
As some of you are aware I won't be able to keep the chairing of this project. I am proposing @patriciaserranog to be chair if any objections. Anyhow I find it is usefull to have her as a CODEOWNER
@camaraproject/admins please send her an invitation

### CODE REVIEW

**Comment by hdamker** [comment]
@TEF-RicardoSerr Thanks a lot for taking care of the succession - highly appreciated! I've invited @patriciaserranog to the CAMARA organization.

@camaraproject/api-backlog_maintainers @camaraproject/api-backlog_codeowners please support the nomination of @patriciaserranog as Codeowner with your approval or raise any objection until Wednesday, August 28th eob.

**Review by caubut-charter — APPROVED** [review]
No objections.

**Review by bigludo7 — APPROVED** [review]

**Comment by hdamker** [comment]
Thanks for the approvals. Waiting for @patriciaserranog to accept the invitation (cc: @TEF-RicardoSerr)

**Review by jgarciahospital — APPROVED** [review]

**Comment by jgarciahospital** [comment]
> Thanks for the approvals. Waiting for @patriciaserranog to accept the invitation (cc: @TEF-RicardoSerr)

should be done, could you check @hdamker ?

**Review by hdamker — APPROVED** [review]
All done here.

**Pull request merged**
