### PR TITLE
New API Proposal - CustomerInsights (renamed from Telco Index)

### LINKED ISSUE #41: New API Proposal - Telco Index
Telco Index API proposal from GSMA OGW Drop 4:

(part of OGW DROP4) The service provides a scoring related to the user's credit profile, calculated based on the information that the operator has about the owner of the associated line. Certain applications or services, like bank accounts, insurers or credit agencies, employ complex risk analysis for their operation. Telcos can calculate a credit scoring for those applications employing owned useful information, including profiling of young people or informal workers, people who do not have much commercial history or market information about who have consumption and credit potential. The service will consider as input a user identifier, like MSISDN, and the document ID or identity Card number, while the output will be the calculated credit scoring for such user.

Related to #42 
Supporting material [API-Overview-TelcoScore.pptx](https://github.com/camaraproject/APIBacklog/raw/61b04b3ced99f64abea3a6abdaced8aee7dbbad5/documentation/SupportingDocuments/API-Overview-TelcoScore.pptx)

### PR DESCRIPTION
**Pull request by jgarciahospital**
#### What type of PR is this?

New API Proposal

#### What this PR does / why we need it:

Telco Scoring API proposal template
Supporting material [API-Overview-TelcoScore.pptx](https://github.com/camaraproject/APIBacklog/raw/61b04b3ced99f64abea3a6abdaced8aee7dbbad5/documentation/SupportingDocuments/API-Overview-TelcoScore.pptx)

#### Which issue(s) this PR fixes:

Fixes #41

### CODE REVIEW

**Comment by KevScarr** [comment]
@jgarciahospital I'll be supporting the Telco Index API initiative from Vodafone.

**Comment by hdamker** [comment]
Please consider already now a more specific name ... "Telco Index" could be all and nothing. From the description it is a credit score, and the description is multiple time using the term "telco credit score". Please indicate clearly within the title what this API proposal is about.

**Comment by jgarciahospital** [comment]
> Please consider already now a more specific name ... "Telco Index" could be all and nothing. From the description it is a credit score, and the description is multiple time using the term "telco credit score". Please indicate clearly within the title what this API proposal is about.

Thanks Herbert for the comments. Also including comments from @tanjadegroot about the generic restriction of not using "Telco specific terms" in API names.

So, for context, and just to have this conversation before TSC to agilize the process, let me include previous proposals:

- Credit Scoring was the initial proposal, but due to legal restrictions in some countries we cannot use neither "Credit" nor "score".
- Telco Index was proposed instead, but it has the two other issues:

1. Not includes a proper specific description of the functionality
2. Uses a Telco term

- Nick (centilion) proposed Trust Index as alternative.

**Comment by bigludo7** [comment]
Hello @jgarciahospital 
Very sorry to be late in this discussion but one point is not clear for me: Does the score algorithm will be part of this API work? 

I saw in your slide deck (slide5) a split that could be considered a first step of this algorithm.
Thanks for the clarification

**Comment by jgarciahospital** [comment]
> Hello @jgarciahospital Very sorry to be late in this discussion but one point is not clear for me: Does the score algorithm will be part of this API work?
> 
> I saw in your slide deck (slide5) a split that could be considered a first step of this algorithm. Thanks for the clarification

Hi @bigludo7 , yes, the idea is to align in a algorithm proposal, similar to what we've done for PopulationDensity, and in this case also align on the value or meaning of the scoring/index results. Otherwise two telcos with the same data could provide different values, and it's really important that we align ourselves to provide homogeneous values and meanings to the customers.

**Pull request merged**
