### PR TITLE
Create APIScopeEnhancement_Device_Status_network_info

### LINKED ISSUE #66: Scope Enhancement: network info for Device Status API Family
# API Scope Enhancement

| **Field** | Description | 
| ---- | ----- |
| API name | [DeviceStatus](https://github.com/camaraproject/DeviceStatus) |
| New API name | NetworkInfo |
| Scope Enhancement owner | Vodafone |
| Scope Enhancement summary | Read-only API to return the name of the operator and network type for an identified network-connected device. Business cases (1) developers can account for the different behaviours they have historically encountered from different network operators (2) developers can determine if the connection is to a virtual operator, which may result in different network capabilities (3) knowing the type of the network the device is connected to (cellular network type, fixed/Wi-Fi, satellite) allows the developer to better estimate network stability. Overall each business case can help improve end user experience|
| Technical viability |  Operator name is static, connection type is available from via NEF. 
| Commercial viability | Server implementations not known - but MNC/MCC lookup available on the UE via programmatic lookup to OS libraries.|
| YAML code available? | YES |
| Validated in lab/productive environments? | NO. |
| Validated with real customers? | NO.|
| Validated with operators? |NO.  |
| Supporters in API Backlog Working Group | Vodafone, Deutsche Telekom  |

### PR DESCRIPTION
**Pull request by Kevsy**
Originally submitted as issue #66

#### What type of PR is this?

Add one of the following kinds:

* enhancement/feature

#### What this PR does / why we need it:

* adds basic network information to response object: network identifiers e.g MNC/MCC, and access medium (4G, 5G, Wi-Fi, satellite etc.)

#### Which issue(s) this PR fixes:

Fixes #66 

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Comment by jgarciahospital** [comment]
HI @Kevsy , is the proposal meant to enhance any of the current Device Status APIs? (Reachability, Roaming or their subscriptions)

If not, even when the proposal seems to be directly targeted to the Device Status family, we'll need to consider it as a new API instead of an enhancement.

**Comment by Kevsy** [comment]
>  is the proposal meant to enhance any of the current Device Status APIs? (Reachability, Roaming or their subscriptions)

HI @jgarciahospital  , I think it could be an enhancement to Reachability, but I think that question is best answered by @NoelWirzius .  Alternatively it may be preferred to be a new API, in which case I can reformat the proposal.

**Comment by jgarciahospital** [comment]
> > is the proposal meant to enhance any of the current Device Status APIs? (Reachability, Roaming or their subscriptions)
> 
> HI @jgarciahospital , I think it could be an enhancement to Reachability, but I think that question is best answered by @NoelWirzius . Alternatively it may be preferred to be a new API, in which case I can reformat the proposal.

Ok, pending to clarify final destination of the API.

**Review by jgarciahospital — APPROVED** [review]
LGTM

**Comment by jgarciahospital** [comment]
PR to be merged as validated in TSC and already work-in-progress in Device Status. @camaraproject/api-backlog_maintainers can anyone review for merging?

**Pull request merged**
