### PR TITLE
New API Enhancement Proposal KYC-Match Scoring

### LINKED ISSUE #45: Scope change for KYC-Match API - Scoring Logic
As evolution of the existing KYC-Match API, scoring logic is proposed to be included:

Current KYC-Match service validates if the information reported by the developer matches with the information that the operator has registered in its systems. Scoring proposal (aka fuzzy logic) is proposed to allow a wider response in which, for the current "false" responses, it will provide a scoring of how close to the actual value is the requested field. <br> <br> E.g. if developer is reporting the name "Clara" while the registered name by operator is "Carla". User may have suffered a typo, and currently the API will directly respond "false", while the scoring mechanism will also report that the requested name is 88% close to the actual name.

Issue raised in backlog group since it modifies original API scope.

PR #46

### PR DESCRIPTION
**Pull request by jgarciahospital**
#### What type of PR is this?

Add one of the following kinds:

* enhancement/feature

#### What this PR does / why we need it:

API template for enhancement on the KYC-Match API

#### Which issue(s) this PR fixes:

Fixes #45

### CODE REVIEW

**Comment by ToshiWakayama-KDDI** [comment]
Hi Jorge,

Looks good to me, except for one point.  According to related discussions in KnowYourCustomer SP, some operators and markets (including Japan) do not need 'Scoring' for KYC Match, so, the enhanced Match API should be able to work without Scoring.  If you could add this point to the template, it would be much appreciated.

(Same comment for Issue #45)

Best regards,
Toshi

**Comment by jgarciahospital** [comment]
To be closed and merged, as agreed in https://github.com/camaraproject/KnowYourCustomer/issues/85

**Comment by eric-murray** [comment]
@camaraproject/api-backlog_codeowners
Agreed to be merged. Needs approval from at least one codeowner.

**Comment by jgarciahospital** [comment]
@caubut-charter can you please approve and merge?

**Pull request merged**
